# Sample workflow for building and deploying a Jekyll and React site to GitHub Pages
name: Deploy Jekyll and React with GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build React and Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build React App
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install React dependencies
        run: |
          cd smahmoodi
          npm install

      - name: Build React
        run: |
          cd smahmoodi
          npm run build

      # Build Jekyll site
      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: |
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build

      # Move React build to Jekyll _site
      - name: Move React Build to Jekyll _site
        run: |
          mv smahmoodi/build/* _site/

      # Upload the final built site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
